/**
 * Mock course catalogue used until the backend lands.
 * TODO: delete this file once GET /courses is live; the shapes match
 * the `Course` typedef in src/types/index.js.
 */

/** @type {import('@/types').Course[]} */
export const MOCK_COURSES = [
  {
    id: 'c-1',
    slug: 'fcps-part-1-medicine-january-batch',
    title: 'FCPS Part-1 Medicine — January Batch',
    category: 'FCPS',
    subtitle: 'Complete basic-science coverage with weekly item-analysis exams.',
    thumbnailUrl: null,
    highlights: [
      '180+ recorded lectures by FCPS-qualified faculty',
      'Weekly SBA & MTF exams with detailed explanations',
      'Full BCPS past-paper bank (2010 – present)',
      'Live problem-solving class every Friday',
      'Printed + PDF lecture notes included',
    ],
    price: 18000,
    discountPrice: 13500,
    duration: '6 months',
    lessonCount: 184,
    enrolledCount: 2140,
    rating: 4.8,
    startsOn: '2026-01-05T00:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'c-2',
    slug: 'fcps-part-2-surgery-clinical-intensive',
    title: 'FCPS Part-2 Surgery — Clinical Intensive',
    category: 'FCPS',
    subtitle: 'Ward-round style clinical training for the final professional stage.',
    thumbnailUrl: null,
    highlights: [
      'Long case & short case demonstration videos',
      'One-to-one mock viva with senior consultants',
      'Operative surgery and instrument sessions',
      'Structured OSCE practice with feedback',
    ],
    price: 25000,
    discountPrice: null,
    duration: '4 months',
    lessonCount: 96,
    enrolledCount: 640,
    rating: 4.9,
    startsOn: '2026-02-01T00:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'c-3',
    slug: 'bcs-health-cadre-full-preparation',
    title: 'BCS (Health) Cadre — Full Preparation',
    category: 'BCS',
    subtitle: 'Preliminary, written and viva in a single guided track.',
    thumbnailUrl: null,
    highlights: [
      'Complete preliminary syllabus in 90 days',
      'Bangla, English, GK & mathematics refreshers',
      '40 full-length model tests with national ranking',
      'Written-answer evaluation by examiners',
      'Viva grooming sessions before the board',
    ],
    price: 12000,
    discountPrice: 8900,
    duration: '5 months',
    lessonCount: 210,
    enrolledCount: 3820,
    rating: 4.7,
    startsOn: '2025-10-05T00:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'c-4',
    slug: 'mbbs-3rd-professional-medicine-final-revision',
    title: 'MBBS 3rd Professional — Final Revision',
    category: 'MBBS',
    subtitle: 'High-yield revision built around the university question pattern.',
    thumbnailUrl: null,
    highlights: [
      'Chapter-wise high-yield note bundle',
      'Card & item exams every alternate day',
      'Formative + summative pattern mock exams',
      'Practical and OSPE preparation sessions',
    ],
    price: 7500,
    discountPrice: 5900,
    duration: '3 months',
    lessonCount: 128,
    enrolledCount: 1560,
    rating: 4.6,
    startsOn: '2025-11-15T00:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'c-5',
    slug: 'mbbs-1st-professional-anatomy-physiology',
    title: 'MBBS 1st Professional — Anatomy & Physiology',
    category: 'MBBS',
    subtitle: 'Foundation year support with dissection-hall oriented teaching.',
    thumbnailUrl: null,
    highlights: [
      'Region-wise anatomy with cadaveric demonstration',
      'Physiology viva question bank',
      'Weekly card exams with model answers',
      'Doubt-clearing sessions twice a week',
    ],
    price: 9000,
    discountPrice: null,
    duration: '8 months',
    lessonCount: 240,
    enrolledCount: 980,
    rating: 4.5,
    startsOn: '2026-01-20T00:00:00.000Z',
    isFeatured: false,
  },
  {
    id: 'c-6',
    slug: 'fcps-part-1-gynae-obs-crash-course',
    title: 'FCPS Part-1 Gynae & Obs — Crash Course',
    category: 'FCPS',
    subtitle: 'Eight-week sprint for candidates sitting the next examination.',
    thumbnailUrl: null,
    highlights: [
      'Daily live classes for eight weeks',
      '3,000+ curated SBA and MTF items',
      'Exam-day strategy and time management drills',
      'Recorded backup of every live session',
    ],
    price: 11000,
    discountPrice: 8500,
    duration: '8 weeks',
    lessonCount: 64,
    enrolledCount: 720,
    rating: 4.7,
    startsOn: '2025-12-01T00:00:00.000Z',
    isFeatured: false,
  },
];

/** Curriculum shown on the course detail page. */
export const MOCK_CURRICULUM = [
  {
    id: 'm-1',
    title: 'Module 1 — Foundation & orientation',
    lessons: [
      { id: 'l-1', title: 'How to approach the syllabus', kind: 'video', durationMinutes: 42, isLocked: false },
      { id: 'l-2', title: 'Exam pattern and marking scheme', kind: 'video', durationMinutes: 28, isLocked: false },
      { id: 'l-3', title: 'Orientation handout', kind: 'pdf', durationMinutes: 10, isLocked: false },
    ],
  },
  {
    id: 'm-2',
    title: 'Module 2 — Core subject lectures',
    lessons: [
      { id: 'l-4', title: 'Cardiovascular system — part 1', kind: 'video', durationMinutes: 68, isLocked: true },
      { id: 'l-5', title: 'Cardiovascular system — part 2', kind: 'video', durationMinutes: 71, isLocked: true },
      { id: 'l-6', title: 'Respiratory system', kind: 'video', durationMinutes: 64, isLocked: true },
      { id: 'l-7', title: 'Lecture notes bundle', kind: 'pdf', durationMinutes: 0, isLocked: true },
    ],
  },
  {
    id: 'm-3',
    title: 'Module 3 — Assessment & revision',
    lessons: [
      { id: 'l-8', title: 'Weekly mock exam 01', kind: 'live', durationMinutes: 90, isLocked: true },
      { id: 'l-9', title: 'Item analysis discussion', kind: 'video', durationMinutes: 55, isLocked: true },
    ],
  },
];
